### Get all games
GET http://localhost:3001/games
Accept: application/json


### Add new game
POST http://localhost:3001/games
Content-Type: application/json

{
  "name": "Uncharted 2",
  "status": "in progress",
  "notes": "Amazing game so far"
}


### Update game
# Replace {game_id} with the actual game _id from the GET request
PUT http://localhost:3001/games/{game_id}
Content-Type: application/json

{
  "name": "Uncharted 2: Updated",
  "status": "completed",
  "notes": "Finally finished this masterpiece!"
}


### Delete game
# Replace {game_id} with the actual game _id
DELETE http://localhost:3001/games/{game_id}